version: "3.9"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}

services:
  docker-in-docker:
    image: docker:20.10-dind
    privileged: true
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    volumes:
      - ${APP_HOST_CODE_PATH}:${APP_CONTAINER_CODE_PATH}
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - backend

  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   WORKSPACE:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  workspace:
    container_name: ${PROJECT_NAME}.workspace
    image: workspace:${ENV_OS}-${ENV_OS_VERSION}
    privileged: true
    tty: true
    build:
      context: ./workspace
      dockerfile: ${ENV_OS}-${ENV_OS_VERSION}.Dockerfile
      args:
        - OS_VERSION=${OS_VERSION}
        - LOCALE=${ENV_LOCALE}
        - LANG=${ENV_LANG}
        - TZ=${ENV_TIMEZONE}
        - GROUP=${PROJECT_NAME}
        - USER=${PROJECT_NAME}
        - PGID=${ENV_PGID}
        - PUID=${ENV_PUID}
        - CHOKIDAR_USEPOLLING=true
        - NPM_REGISTRY=${WORKSPACE_NPM_REGISTRY}
        - NPM_FETCH_RETRIES=${WORKSPACE_NPM_FETCH_RETRIES}
        - NPM_FETCH_RETRY_FACTOR=${WORKSPACE_NPM_FETCH_RETRY_FACTOR}
        - NPM_FETCH_RETRY_MINTIMEOUT=${WORKSPACE_NPM_FETCH_RETRY_MINTIMEOUT}
        - NPM_FETCH_RETRY_MAXTIMEOUT=${WORKSPACE_NPM_FETCH_RETRY_MAXTIMEOUT}
        - NVM_NODEJS_ORG_MIRROR=${WORKSPACE_NVM_NODEJS_ORG_MIRROR}
        - NODE_VERSION=${NODE_VERSION}
        - NVM_VERSION=${NVM_VERSION}
        - YARN_VERSION=${YARN_VERSION}
        - INSTALL_GIT_PROMPT=${WORKSPACE_INSTALL_GIT_PROMPT}
        - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
        - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
        - INSTALL_OH_MY_ZSH=${SHELL_OH_MY_ZSH}
        - INSTALL_PM2=${WORKSPACE_INSTALL_PM2}
        - INSTALL_PYTHON3=${WORKSPACE_INSTALL_PYTHON3}
        - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
        - INSTALL_SSH=${WORKSPACE_INSTALL_SSH}
        - INSTALL_SUPERVISOR=${WORKSPACE_INSTALL_SUPERVISOR}
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - ${APP_HOST_CODE_PATH}:${APP_CONTAINER_CODE_PATH}${APP_CONTAINER_CODE_FLAG}
      - docker-in-docker:/certs/client
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${SSH_PORT}:22"
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
  
  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   CACHE ENGINES:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  #────: Redis
  redis:
    container_name: ${PROJECT_NAME}.redis
    image: redis:${REDIS_VERSION}
    build: 
      context: ./cache-engines/redis
      args:
        - VERSION=${REDIS_VERSION}
    volumes:
      - ${APP_HOST_STORAGE}/${PROJECT_NAME}/redis/data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  
  redis-webui:
    container_name: ${PROJECT_NAME}.redis-webui
    build: 
      context: ./cache-engines/redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    networks:
      - backend
    depends_on:
      - redis
  
  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   DEVOPS:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  #────: Swagger
  swagger-editor:
    # container_name: Swagger-Editor
    image: swagger/editor:${SWAGGER_EDITOR_VERSION}
    build: 
      context: ./cicd/swagger
      dockerfile: editor.Dockerfile
      args:
        - VERSION=${SWAGGER_EDITOR_VERSION}
    ports:
      - ${SWAGGER_EDITOR_PORT}:8080
    networks:
      - backend
  
  swagger-ui:
    # container_name: Swagger-UI
    image: swagger/ui:${SWAGGER_UI_VERSION}
    build: 
      context: ./cicd/swagger
      dockerfile: ui.Dockerfile
      args:
        - VERSION=${SWAGGER_UI_VERSION}
    environment:
      - API_URL=${SWAGGER_API_URL}
    ports:
      - ${SWAGGER_UI_PORT}:8080
    networks:
      - backend

  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   DATABASE MANAGEMENT SYSTEMS:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  #────: MSSQL
  mssql:
    container_name: ${PROJECT_NAME}.mssql
    image: mssql:${MSSQL_VERSION}
    build:
      context: ./dbms/mssql
      args:
        - VERSION=${MSSQL_VERSION}
        - LOCALE=${ENV_LOCALE}
        - LANG=${ENV_LANG}
        - TZ=${ENV_TIMEZONE}
    environment:
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_COLLATION=${MSSQL_COLLATION}
      - SA_PASSWORD=${PROJECT_NAME}${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ${APP_HOST_STORAGE}/${PROJECT_NAME}/mssql:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend
  
  #────: PostgreSQL
  postgres:
    container_name: ${PROJECT_NAME}.postgres
    image: postgres:${POSTGRESQL_VERSION}
    build: 
      context: ./dbms/postgresql
      args:
        - VERSION=${POSTGRESQL_VERSION}
        - LOCALE=${ENV_LOCALE}
        - LANG=${ENV_LANG}
        - TZ=${ENV_TIMEZONE}
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${PROJECT_NAME}${POSTGRESQL_PASSWORD}
      - POSTGRES_INITDB_ARGS=${POSTGRESQL_INITDB_ARGS}
      - GITLAB_POSTGRESQL_INIT=${GITLAB_POSTGRESQL_INIT}
      - TEAMCITY_POSTGRESQL_INIT=${TEAMCITY_POSTGRESQL_INIT}
    volumes:
      - ${APP_HOST_STORAGE}/${PROJECT_NAME}/postgres/data:/var/lib/postgresql/data
      - ${POSTGRESQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT}:5432"
    networks:
      - backend

  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   WEB APPLICATION SERVERS:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  #────: Tomcat
  tomcat:
    container_name: ${PROJECT_NAME}.tomcat
    image: tomcat:${TOMCAT_VERSION}
    build: 
      context: ./app-server/tomcat
      args:
        - VERSION=${TOMCAT_VERSION}
        - LOCALE=${ENV_LOCALE}
        - LANG=${ENV_LANG}
    environment:
      - PROFILE=${ENV_PROFILE}
      - TZ=${ENV_TIMEZONE}
    volumes:
      # - ${APP_HOST_STORAGE}/${PROJECT_NAME}/tomcat/webapps:${TOMCAT_PATH}/webapps
      # - ${APP_HOST_CODE_PATH}/out/artifacts/ROOT:${TOMCAT_PATH}/webapps
      - ${APP_HOST_STORAGE}/${PROJECT_NAME}/tomcat/logs:${TOMCAT_PATH}/logs
      - ./app-server/tomcat/conf:${TOMCAT_PATH}/conf
    ports:
      - "${TOMCAT_HTTP_PORT}:8080"
    networks:
      - frontend
      - backend

  #
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #   WEB SERVERS:
  #────────────────────────────────────────────────────────────────────────────────────────────────────
  #
  #────: Apache
  # apache:
  #   # container_name: Apache
  #   image: apache:${APACHE_VERSION}
  #   build: 
  #     context: ./web-server/apache2
  #     args:
  #       - VERSION=${APACHE_VERSION}
  #       - APACHE_PATH=${APACHE_PATH}
  #       - LOCALE=${ENV_LOCALE}
  #       - LANG=${ENV_LANG}
  #       - TZ=${ENV_TIMEZONE}
  #       - CONNECTOR_VERSION=${TOMCAT_CONNECTOR_VERSION}
  #       - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
  #       - INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}
  #       - INSTALL_TOMCAT_CONNECTOR=${APACHE_INSTALL_TOMCAT_CONNECTOR}
  #   volumes:
  #     - ${APP_HOST_CODE_PATH}:${APP_CONTAINER_CODE_PATH}${APP_CONTAINER_CODE_FLAG}
  #     - ${APP_HOST_STORAGE}/${PROJECT_NAME}/apache/logs:${APACHE_PATH}/logs
  #     # - ${APACHE_SSL_PATH}:/etc/apache2/ssl
  #     - ./web-server/apache2/conf:${APACHE_PATH}/conf
  #   ports:
  #     - "${WEB_HTTP_PORT}:80"
  #     - "${WEB_HTTPS_PORT}:443"
  #   networks:
  #     - frontend
  #     - backend
  #   # depends_on:
  #     # - workspace

  #────: Nginx
  nginx:
    container_name: ${PROJECT_NAME}.nginx
    image: nginx:${NGINX_VERSION}
    build:
      context: ./web-servers/nginx
      args:
        - UPSTREAM_CONTAINER=${NGINX_UPSTREAM_CONTAINER}
        - UPSTREAM_PORT=${NGINX_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - TZ=${ENV_TIMEZONE}
    volumes:
      - ${APP_HOST_CODE_PATH}:${APP_CONTAINER_CODE_PATH}${APP_CONTAINER_CODE_FLAG}
      - ${APP_HOST_STORAGE}/${PROJECT_NAME}/nginx/logs:/var/log/nginx
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${WEB_HTTP_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
      - "${VARNISH_BACKEND_PORT}:81"
    networks:
      - frontend
      - backend
      