version: "3.9"

networks:
  frontend:
    name: ${ENV_NAME}_frontend
    driver: ${NETWORKS_DRIVER}
  backend:
    name: ${ENV_NAME}_backend
    driver: ${NETWORKS_DRIVER}

volumes:
  docker-in-docker:
    name: ${ENV_NAME}_dind
    driver: ${VOLUMES_DRIVER}

services:
  docker-in-docker:
    container_name: ${ENV_NAME}-dind
    image: docker:20.10-dind
    privileged: true
    volumes:
      - ${APP_CODE_HOST_PATH}:${APP_CODE_CONTAINER_PATH}
      - docker-in-docker:/certs/client
    environment:
      - DOCKER_TLS_SAN=DNS:docker-in-docker
    expose:
      - 2375
    networks:
      - backend

  #
  #───────────────────────────────────────────────────────────────────────────────
  # WORKSPACE:
  #───────────────────────────────────────────────────────────────────────────────
  #
  workspace:
    container_name: ${ENV_NAME}-workspace
    image: ${ENV_NAME}_workspace
    tty: true
    build:
      context: ./workspace
      dockerfile: ${ENV_OS}.local.Dockerfile
      args:
        - OS_VERSION=${OS_VERSION}
        - ENV_NAME=${ENV_NAME}
        - ENV_MODE=${ENV_MODE}
        - PGID=${WORKSPACE_PGID}
        - PUID=${WORKSPACE_PUID}
        - TZ=${ENV_TIMEZONE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_HOST_PATH}:${APP_CODE_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
      - docker-in-docker:/certs/client
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
  
  #
  #───────────────────────────────────────────────────────────────────────────────
  # openJDK:
  #───────────────────────────────────────────────────────────────────────────────
  #
  openjdk:
    container_name: ${ENV_NAME}-openjdk
    image: ${ENV_NAME}_openjdk
    build:
      context: ./openjdk
      dockerfile: local.Dockerfile
    volumes:
      - ${APP_CODE_HOST_PATH}:${APP_CODE_CONTAINER_PATH}${APP_CODE_CONTAINER_FLAG}
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME=${JAVA_FAKETIME}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${JAVA_PORT}:8080"
    networks:
      - backend
    depends_on:
      - workspace
    links:
      - docker-in-docker