#
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#━━━━IMAGE SETUP━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
ARG MONGODB_VERSION
FROM mongo:${MONGODB_VERSION}

LABEL maintainer="Anthony Oh <incyverse@gmail.com>"

# COPY mongodb.conf /usr/local/etc/mongo/mongo.conf

VOLUME /data/db /data/configdb

CMD [ "mongod" ]

EXPOSE 27017