#!/bin/bash
set -e

if [ "$TEAMCITY_INIT" == 'true' ]; then
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $TEAMCITY_USER WITH PASSWORD '$TEAMCITY_PASS';
    CREATE DATABASE $TEAMCITY_DATA WITH OWNER $TEAMCITY_USER;
    GRANT ALL PRIVILEGES ON DATABASE $TEAMCITY_DATA TO $TEAMCITY_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $TEAMCITY_USER;
    ALTER ROLE $TEAMCITY_USER CREATEROLE SUPERUSER;
EOSQL
echo
fi
