#!/bin/bash
set -e

# ALTER ROLE pcms CREATEROLE;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	SET TIMEZONE TO '$TZ';
	REVOKE ALL ON DATABASE postgres FROM PUBLIC;
	CREATE USER pcms WITH PASSWORD 'pcms(!)2022';
	CREATE DATABASE pcms WITH OWNER pcms;
	GRANT ALL PRIVILEGES ON DATABASE pcms TO pcms;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pcms;
EOSQL

psql -v ON_ERROR_STOP=1 --username "pcms" --dbname "pcms" <<-EOSQL
	REVOKE ALL ON DATABASE pcms FROM PUBLIC;
EOSQL
