#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER pcms WITH PASSWORD 'pcms(!)2022';
	CREATE DATABASE pcms;
	GRANT ALL PRIVILEGES ON DATABASE pcms TO pcms;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pcms;
	ALTER ROLE pcms CREATEROLE SUPERUSER;
EOSQL
echo
