#!/bin/bash
set -e

if [ "$GITLAB_INIT" == 'true' ]; then
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GITLAB_USER WITH PASSWORD '$GITLAB_PASS';
    CREATE DATABASE $GITLAB_DATA WITH OWNER $GITLAB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $GITLAB_DATA TO $GITLAB_USER;
    ALTER ROLE $GITLAB_USER CREATEROLE SUPERUSER;
EOSQL
echo
fi
