#!/bin/bash

if [ "$TEAMCITY_POSTGRES_INIT" == 'true' ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER $TEAMCITY_POSTGRES_USER WITH PASSWORD '$TEAMCITY_POSTGRES_PASSWORD';
		CREATE DATABASE $TEAMCITY_POSTGRES_DATABASE;
		GRANT ALL PRIVILEGES ON DATABASE $TEAMCITY_POSTGRES_DATABASE TO $TEAMCITY_POSTGRES_USER;
		ALTER ROLE $TEAMCITY_POSTGRES_USER CREATEROLE SUPERUSER;
	EOSQL
	echo
fi
